### ISSUE TITLE
Merge luks2 support from upstream

### ISSUE THREAD

**Issue by aaomidi** [endeavouros-team/calamares#12]
Context: https://twitter.com/hipsterelectron/status/1648167820495142915, https://mjg59.dreamwidth.org/66429.html

https://github.com/calamares/calamares/pull/2047

Also I've made an issue asking to default to luks2 https://github.com/calamares/calamares/issues/2127

And a PR to https://invent.kde.org/system/kpmcore/-/merge_requests/43

**Comment by killajoe** [comment]
we will use LUKS 2 up from next release
