### ISSUE TITLE
Pacstrap Calamares error 

### ISSUE THREAD

**Issue by Boria138** [endeavouros-team/calamares#14]
I am using your script pacstrap_calamares (thank you for it) to install my distribution as a module but I have a question if I can install packages in pacstrap using a script instead of a module ? Let me explain I have a script which finds out what kind of processor a person has and uses this to install the package ucode I have to do the following command
`sh pacstrap_calamares -c ${ROOT} intel-ucode` but the script complains that intel ucode is not the directory, is it possible to fix this ?

**Comment by dalto8** [comment]
You don't need to pacstrap intel-ucode.  You can use a script to install it in a subsequent step using the shellprocess module.

pacstrap allows you to install the minimal packages needed to get a working environment.  After that, you can use the working environment to install packages or perform other actions.

**Comment by Boria138** [comment]
> You don't need to pacstrap intel-ucode. You can use a script to install it in a subsequent step using the shellprocess module.
> 
> pacstrap allows you to install the minimal packages needed to get a working environment. After that, you can use the working environment to install packages or perform other actions.

So I have to run the script through a shell process and install packages through pacman -S and then the packages will be installed in the main system and not in the live iso ?

**Comment by dalto8** [comment]
> So I have to run the script through a shell process and install packages through pacman -S and then the packages will be installed in the main system and not in the live iso ?

If you are using a script to determine which ucode package to install then yes, a shellprocess is the way to go.

In the shellprocess.conf there is a setting named `dontChroot`.  If you set it to `false` then the script will be run in the target system.

Getting used to using shellprocess modules will be generally useful for you.  It will allow you to customize the install.

**Comment by Boria138** [comment]
Thanks for your help I guess the issue can be closed
