### ISSUE TITLE
Add firewall setup option to the installer

### ISSUE THREAD

**Issue by xa9e** [endeavouros-team/calamares#16]
It's a common problem with closed ports on a fresh install for EndeavourOS users, especially for me.  By default, most Linux distros do not have firewalls installed and enabled. This involves a long troubleshooting process when working with network applications, until you understand or remember that there is a firewall.   

The solution is to add an option to the EndeavourOS installer, so users will always see that a firewall is going to be installed and will be able to disable it while installing if they don't see any purpose for it.

**Comment by dalto8** [comment]
Thanks for the feedback!

> By default, most Linux distros do not have firewalls installed and enabled.

In the past that was true, but in 2023 most of the major Linux distro ship with a firewall installed and enabled.  OpenSUSE, Fedora and RedHat for example all ship with a firewall.  There are many other distros that do the same.

We offer the option to not install the firewalld on the package selection(netinstall) page.

I understand that this caused in issue in your specific case but it isn't really practical to highlight every single thing that might be concerning to someone.

Perhaps we can look at organizing the package selection page a little differently to make it more obvious.

**Comment by killajoe** [comment]
![Screenshot_20230817_220710-1](https://github.com/endeavouros-team/calamares/assets/16797647/f864fd7d-d332-4055-a80c-554edab6ec39)
it could be shown like this

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/calamares/commit/a9361d1bca25fdfba0d95507cb9c8bef8b8f89ae
