### ISSUE TITLE
reiserfs

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/calamares#24]
(https://github.com/endeavouros-team/calamares/blob/52f61868e4d1a5bca62673cba2516ad42c864b8c/data/eos/modules/pacstrap.conf#L47)

should we remove this from getting installed by default for all installs? and may also remove support from ISO ?

**Comment by dalto8** [comment]
If memory serves, the filesystem list in Calamares is just the list of all filesystems that are supported by kpmcore.

I think if we remove that from the ISO, it will result in broken installs if someone selects reiserfs.

I wonder if a better solution would be to only install the filesystem packages that the user selects as part of the install.  That would be a bit of work to implement though.

**Comment by killajoe** [comment]
yea what we currently have is simply adding support for all common used filesystems.. 
Wonder if it is possible that kpm core is not showing reiserfs if that package is not installed..

**Comment by killajoe** [comment]
![2023-10-15_18-19](https://github.com/endeavouros-team/calamares/assets/16797647/9854ab1a-308b-4aa5-a871-4871b6d6bd4e)
![2023-10-15_18-18](https://github.com/endeavouros-team/calamares/assets/16797647/f1abc30c-97a5-4c17-bf48-b770445643ee)
in both it does only show option for reiserfs if the progs are installed.. if not it is not there..   as a choosable option..
