### ISSUE TITLE
Include noto-color-emoji or any other emoji font as a package in the software selection section of the installer

### ISSUE THREAD

**Issue by ghost** [endeavouros-team/calamares#25]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when
An emoji font should be installed by default as they are very commonly used and most desktop Non-DIY OSes include them by default. Many users would never know that they are missing an emoji font on their OS without asking online.
**Describe the solution you'd like**
Include noto-fonts-emoji-fontconfig^AUR package as part of default online and offline install which includes the noto-fonts-emoji package and enable it in fontconfig. Use noto-color-emoji emoji font as it supports the most applications in Linux
**Describe alternatives you've considered**
ttf-twemoji and ttf-joypixels could also be included but if you want to use an emoji font other than noto-color-emoji, then I wouldn't ttf-twemoji since it is part of the AUR and therefore not maintained by the Arch Linux team whilst ttf-joypixels is. 
**Additional context**
I installed endeavouros and noticed that my emojis weren't displayed properly and since I am an intermediate user, I immediately knew that I was missing an emoji font.

**Comment by killajoe** [comment]
In the past we where limited to ISO filesize as we where using GitHub for initial uploads, including emoji package was a problem already so decision was to not include for the benefit of other tools to be included.   
Not sure if we should use noto-color-emoji-fontconfig @manuel-192 @dalto8 ?

**Comment by dalto8** [comment]
I personally don't think we should bring in an AUR package to our base install for emoji fonts.

If we think this functionality is something we *should* have in our base install, we should probably add an appropriate emoji font package from the repos.

We just need to be aware that many of users will see this as bloat so we need to continue to balance usability out of the box with limiting our install size.

**Comment by killajoe** [comment]
Yes indeed.. baisically it is not needed by default.. and it does not really adding any functionality aside from showing emojies in terminal and may in some applications like titlebar on using a browser..  and in addition if everything is set up automatically users will not know about how it is done too. This is still arch based and the arch way is to set this up by understanding how it works, and if you do not know.. ask the friendly community or read the wiki..

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/calamares/commit/087dc64496ffb1c88e456f5966a0e9df15403b32
i added basic emoji support by adding noto-fonts-emoji

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/calamares/commit/087dc64496ffb1c88e456f5966a0e9df15403b32
i added basic emoji support by adding noto-fonts-emoji
