### ISSUE TITLE
Add plymouth with EndeavourOS logo to package selection screen

### ISSUE THREAD

**Issue by ghost** [endeavouros-team/calamares#29]
**Is your feature request related to a problem? Please describe.**
The boot message look quite unprofessional and they are shown by default when booting or logging out.

**Describe the solution you'd like**
Give [plymouth](https://wiki.archlinux.org/title/plymouth) package as an option of packages to install in the respective section of the online installer. If it is selected as an package to install during installation, then after installing all the. It is up to you guys to decide if it should be part of the installation by default or not but I recommend it not be part of the default online install since users won't know how to show the boot message if it is enabled but still be an option. If the user has selected it to be installed during OS installation, then the installer configures plymouth for the user and uses the BGRT plymouth theme which IMO looks the most professional and is plymouth's default theme used on most distros. It uses the Adwaita spinner icon which spins during boot and if you want to go the extra mile can be replaced by the KDE Breeze spinner icons in `plymouth-theme-bgrt-breeze plymouth` theme package for more system coherence which is installed by default if the Plasma desktop is selected during default install. Once again if you want to go the further mile if XFCE or Mate or Cinnamon or Budgie or GNOME (if GNOME uses the Qogir theme by default in eos, if it uses adwaita or adw-gtk3-theme by default to keep more in line with the libadwaita theme then please create the package `plymouth-theme-bgrt-adwaita` are selected as the DE during online install then it can be replaced with Qogir spinner icons and a separate plymouth theme package can be created for them called plymouth-theme-bgrt-qogir These icons need to be replaced in the default archlinux plymouth package at `/usr/share/plymouth/themes/spinner/`.  At the bottom of the splash screen the there is the distro's full logo which is provided by the plymouth package as `/usr/share/plymouth/themes/spinner/watermark.png`. It's dimensions should be 256 × 68. Then the installer should run `sudo plymouth-set-default-theme -R bgrt` and then `sudo dracut --hostonly --no-hostonly-cmdline /boot/initramfs-*.img --force where * is the name of the default kernel package
`
**Describe alternatives you've considered**
You could add the `quiet fastboot fbcon=nodefer` kernel parameters which hides everything (motherboard vendor logo and boot messages) during boot and log out at least on Intel CPUs because by default the logo would also be shown during log out with plymouth. I don't know if it can be used in conjunction with plymouth.I also don't know how to hide plymouth during log out but some distros do like GeckoLinux so you could replicate that here. 

**Additional Context**
![Here is the how it looks with the default adwaita spinner. Note that this is a rough recreation in kolourpaint so the positioning is a bit wrong](https://github.com/endeavouros-team/calamares/assets/95931540/3d961601-2288-4153-aad3-6875fc68dad4)

**PS:** Sorry for poor english, I have schiziophrenia and OCD.

**Comment by dalto8** [comment]
In prior versions we used `quiet` and hid the messages.

We decided it was better for people to see the messages by default so it was more clear what was happening when there was an issue.

At the same time, if people wish to hide the messages and have nice splash screen, they are free to do that themselves.  In general, we provide a usable starting point from the installer.  From there, each person can customize it to meet their own desires.

**Comment by killajoe** [comment]
I can only follow up with dalto, the decision is to keep installation and installed defaults as simple as possible, that is what makes EndeavourOS stable and keep maintainance minimal. 

And as dalto already say we decided to show the boot messages by default from experience in helping on issues, if users are not experienced they will simply say onmly something like black screen or even i killed my OS.. if they have the boot messages they always have something they see and can do a photo what gives helpers a starting point.

**Comment by ghost** [comment]
You can tell the users how to show the boot message when using plymouth

**Comment by dalto8** [comment]
For the reasons discussed above, this is not a direction we currently plan to pursue.

**Comment by ghost** [comment]
> I can only follow up with dalto, the decision is to keep installation and installed defaults as simple as possible, that is what makes EndeavourOS stable and keep maintenance minimal.
> 
> And as dalto already say we decided to show the boot messages by default from experience in helping on issues, if users are not experienced they will simply say only something like black screen or even i killed my OS. if they have the boot messages they always have something they see and can do a photo what gives helpers a starting point.

Like I said, the Plymouth package can be optional by not being a part of the package selection screen (if you want it to be, then you can include a tool-tip for it, that lets users know how they can show boot messages with it using the esc key) and offline install or it can be a part of the EndeavourOS software repository for users who know about Plymouth so they still can install it. Those users will know how they can show the boot messages with it running but just in case you can also include some text in the descriptions letting users know how they can show the boot messages.

**Comment by killajoe** [comment]
We do not say it would not be possible, but we say we will not go that direction.
Users can use plymouth if the y want, but adding it as an option will involve extra maintainment and development time, and will cause issues from time to time. 

The goal for EndeavourOS is to keep the install as minimal as possible, also to make the OS more stable.
