### ISSUE TITLE
windowsbootentry module

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/calamares#31]
https://github.com/endeavouros-team/calamares/blob/55b1b4d4ba003e81d68146d77d3e88907c03769c/src/modules/windowsbootentry/main.py#L179

is this correct? 
`f"EFI`

**Comment by dalto8** [comment]
It looks OK to me.  What is wrong with it?

**Comment by killajoe** [comment]
someone mentioned his windows boot entry was set to /efi/Microsoft instead of /EFI/Microsoft installing with grub.. so was checking the module ..

**Comment by dalto8** [comment]
That is just an warning message.  It is what gets sent to the log so it wouldn't impact that either way.

For grub, the path is generated by os-prober.

**Comment by killajoe** [comment]
> For grub, the path is generated by os-prober.

this was what i remembered too was not sure, still strange report also on the forum now.
