### ISSUE TITLE
Virtual console service errors during boot from New Zealand

### ISSUE THREAD

**Issue by binarykitchen** [endeavouros-team/calamares#49]
New here and checking out EndeavourOS for first time. It's remarkable. Most works fine, except this one error during boot:

```
Jun 26 09:32:03 M1 systemd[1]: systemd-vconsole-setup.service: Main process exited, code=exited, status=1/FAILURE
Jun 26 09:32:03 M1 systemd[1]: systemd-vconsole-setup.service: Failed with result 'exit-code'.
Jun 26 09:32:03 M1 systemd[1]: run-credentials-systemd\x2dvconsole\x2dsetup.service.mount: Deactivated successfully.
Jun 26 09:32:03 M1 systemd-vconsole-setup[164]: /usr/bin/loadkeys failed with exit status 1.
Jun 26 09:32:03 M1 systemd-vconsole-setup[171]: loadkeys: Unable to open file: nz: No such file or directory
Jun 26 09:32:03 M1 systemd-vconsole-setup[457]: loadkeys: Unable to open file: nz: No such file or directory
Jun 26 09:32:03 M1 systemd-vconsole-setup[451]: /usr/bin/loadkeys failed with exit status 1.
```

That's from the logs. And now a photo, happens every time I boot:
![342974001-91887f78-b008-4461-aa1e-1ccb1a2486d6](https://github.com/endeavouros-team/calamares/assets/177641/44abb7c4-7b8b-4f59-9e3a-8e78e2ef5276)

To reproduce, hard to say. I'm from New Zealand and have set up most locales/configs referring to en-NZ, not en-US.

Happy to provide more outputs, logs, to help you to narrow down that issue. Peace out.

**Comment by binarykitchen** [comment]
Tried to run that service by myself:

```
~ ❯❯❯ systemctl status systemd-vconsole-setup.service start                                                                                                                                                    ✘ 1 
Unit start.service could not be found.
```

**Comment by killajoe** [comment]
I do not really get what is the actual issue? only warning error on boot log or any real issue?
What is your ` locale`  output?

**Comment by killajoe** [comment]
`systemctl status systemd-vconsole-setup.service`
This is not to start manually..

**Comment by killajoe** [comment]
closed as of no action
