### ISSUE TITLE
data/eos/calamares-translations.txt uses inconsistent naming schema

### ISSUE THREAD

**Issue by BenjaminLindberg** [endeavouros-team/calamares#52]
Hi, so i noticed that this file mostly refers to Swedish using the ISO code `sv`, but sometimes it mentions it as `se` which is not the correct language code for Swedish (atleast in ISO 639). 

This makes me wonder if this is a feature, or a simple mistake. I noticed it when i took a quick glance on the file to see if there was any Swedish translation missing so i haven't tested it to see if it affects the translations in any way.

**Comment by BenjaminLindberg** [comment]
https://github.com/endeavouros-team/calamares/pull/53

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/calamares/commit/5b9ad8d397f8f918a4010f1bf097472157c1c66b
