### ISSUE TITLE
GRUB does not remember the last used item because 45_eos_windows in /etc/grub.d/

### ISSUE THREAD

**Issue by EvilrootNix** [endeavouros-team/calamares#58]
The admin of telegram tell me that report the bug here, because EOS does not package GRUB.

I was trying to get GRUB to remember the last used entry without any luck, even setting GRUB_SAVEDEFAULT=true and GRUB_DEFAULT=saved (at the same time) without success, but I had also noticed that when activating os_prober detection, 2 windows entries were generated in the menu.
I tried moving 45_eos_windows to /root and now os_prober works correctly when updating grub and also remembers the last used one. I suppose that during the installation it detected windows 11 in the other partition, added the entry and for reasons I don't understand, it creates a conflict with os_prober and also with the operation of GRUB and remembering the last used entry.

The content of 45_eos_windows is:
#!/bin/sh
exec tail -n +3 $0

menuentry 'Windows Boot Manager (on /dev/nvme0n1p1)' --class windows --class os $menuentry_id_option 'osprober-efi-B8D9-0EC1' {
	insmod part_gpt
	insmod fat
	search --no-floppy --fs-uuid --set=root B8D9-0EC1
	chainloader /EFI/Microsoft/Boot/bootmgfw.efi

**Comment by dalto8** [comment]
Yes, the installer expects you will not use os-prober as we don't recommend that.  Instead it creates a manual entry for Windows.  If you enable os-prober, you should delete this entry.  That is expected behavior.

**Comment by EvilrootNix** [comment]
> Yes, the installer expects you will not use os-prober as we don't recommend that. Instead it creates a manual entry for Windows. If you enable os-prober, you should delete this entry. That is expected behavior.

Ok fine with it, but the malfunction of last used item un grub menu?

Why does not recommend os_prober?

**Comment by dalto8** [comment]
That is working here.  I am not sure why it wasn't working for you.

**Comment by EvilrootNix** [comment]
Well, I'll try in a VM to see if it happens again. Thanks.

**Comment by killajoe** [comment]
hi there, 
I do testify the situation here too, and I can not confirm any issue with it, grub feature "save last chosen" is not effected by the presence of this file. 
And os-prober is disabled by default from upstream of the grub package too.

**Comment by killajoe** [comment]
Added some details to the default Info Page here:
![2024-10-30_09-53](https://github.com/user-attachments/assets/454d3bce-b534-4f55-83d6-5fdd93af036c)
https://endeavouros.com/
