### ISSUE TITLE
Add an option to install without wiping /home

### ISSUE THREAD

**Issue by FlooferLand** [endeavouros-team/calamares#59]
**Is your feature request related to a problem? Please describe.**
Reinstalling Linux is always very frustrating, as there's no convenient supported way of keeping your home directory

**Describe the solution you'd like**
An option on the installer to let you install EndeavourOS on top of an already-existing install, while keeping the home directory.
This would mean not formatting the partition and instead, deleting every folder that isn't `/home`
This would be safe, as nothing tries to write to the /home partition during installation.

**Describe alternatives you've considered**
- BTRFS works, but it isn't officially supported by the installer and requires ugly workarounds
- Backing up the home directory isn't viable for a lot of people, either because of space requirements _(its impossible to create a new 100 GB partition when those GB are already in use)_, because it takes a long time, or because it wipes out your `created` timestamps for every file as most Linux filesystems base it off the time a file was created on-disk
- Separate home partitions are only meant to be used if you want to place your home on another drive. Separate home and root partition on the same drive can cause one partition to run out of space, which requires the user to risk losing all of their data by resizing and moving their partitions to assign more space to the partition needing it.

**Additional context**
Windows already does this, and it makes reinstalling the OS for the user incredibly convenient.
This would not keep installed programs or configs, unless they were placed in the home directory.

**Comment by dalto8** [comment]
Calamares does not support this.

However, there is a supported way of keeping your `/home`.  That is to put it in a separate partition.  This is true on almost any distro.  I understand why you don't like this option.  I don't do that either.

Honestly, I think it would be pretty poor behavior for an installer to wipe out all directories except for `/home` within a single partition.
